import fs from 'node:fs';
import path from 'node:path';
const root=import.meta.dirname;
const data=n=>JSON.parse(fs.readFileSync(path.join(root,n+'.json'),'utf8'));
const home=data('home'), people=data('people'), papers=data('papers'), research=data('research'), posts=data('posts'), opportunities=data('opportunities');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=[['','Home'],['our-team','Our Team'],['research','Research'],['publications','Publications'],['news','News'],['opportunities','Opportunities']];
const themes=[['Energy Planning and Development','Designing inclusive and just energy systems that prioritize social equity in access, affordability, and agency in both the Global North and South.'],['End-Use Electrification and Energy Access','Investigating electric mobility, electric cooking, and productive uses of energy to support development goals.'],['Power System Reliability & Resilience','Planning for reliable, resilient, and climate-informed grid systems—urban and rural, centralized and decentralized.'],['Interdisciplinary and Contextual Approaches','Integrating technical, behavioral, and institutional insights to inform energy policy and technology adoption.']];
let prefix='./';const url=s=>prefix+(s?s+'/':'');const img=(src,alt,cls='',eager=false)=>`<img src="${prefix+esc(src)}" alt="${esc(alt)}" class="${cls}" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;
const link=(href,label)=>`<a href="${esc(href)}">${esc(label)}</a>`;
const themeGrid=()=>`<div class="themes">${themes.map((t,i)=>`<article class="theme"><span class="number">0${i+1}</span><h3>${esc(t[0])}</h3><p>${esc(t[1])}</p></article>`).join('')}</div>`;
const newsGrid=(list)=>`<div class="news-grid">${list.map(p=>`<a class="news-card" href="${url('post/'+p.slug)}">${p.images?.length?img(p.images[0],p.title):'<div class="no-image"></div>'}<h3>${esc(p.title)}</h3><p>${esc((p.paragraphs?.[0]||'').slice(0,190))}${(p.paragraphs?.[0]?.length||0)>190?'…':''}</p><span class="read">Read the story ↗</span></a>`).join('')}</div>`;
function render(slug){
 if(!slug)return `<div class="wrap"><section class="hero"><div><p class="eyebrow">IDEAS Research Lab · University of Washington</p><h1>Energy systems.<br>Centered on society.</h1><p class="intro">${esc(home.blocks[1].text)}</p><a class="button" href="${url('research')}">Explore our research <span aria-hidden="true">↗</span></a></div><figure>${img(home.hero,'IDEAS Lab field research', '',true)}<figcaption>${esc(home.blocks[0].text)}</figcaption></figure></section></div><section class="section tint"><div class="wrap"><div class="statement"><h2>${esc(home.blocks[2].text)}</h2><p>${esc(home.blocks[3].text.split('Our core research themes')[0])}</p></div>${themeGrid()}</div></section><section class="section"><div class="wrap"><div class="section-head"><h2>News &amp; events</h2><a href="${url('news')}">All updates ↗</a></div>${newsGrid(posts.slice(0,3))}</div></section><section class="section tint"><div class="wrap feature-paper"><div><p class="eyebrow">Latest publications</p><h2>Research in practice.</h2></div><div><h3>${esc(home.blocks[6].text)}</h3><p>${esc(home.blocks[7].text)}</p><p class="authors">${esc(home.blocks[8].text)}</p><a href="${url('publications')}">Explore our publications ↗</a></div></div></section>`;
 if(slug==='our-team')return `<div class="wrap"><div class="page-intro"><p class="eyebrow">Meet the team</p><h1>Our research group</h1><p>${esc(data('our-team').blocks[2].text.toLowerCase().replace(/^w/,'W'))}.</p></div><div class="people">${people.map(p=>`<article class="person">${img(p.image,p.name)}<div><h2>${esc(p.name)}</h2><div class="role">${esc(p.role)}</div><p>${esc(p.bio)}</p>${link(p.url,'Profile ↗')}</div></article>`).join('')}</div></div>`;
 if(slug==='research')return `<div class="wrap"><div class="page-intro"><p class="eyebrow">What we work on</p><h1>Research &amp; initiatives</h1></div>${themeGrid()}<div class="section-head section"><h2>Projects &amp; collaborations</h2><a href="${url('publications')}">See publications ↗</a></div><div class="projects">${research.blocks.slice(2,11).map(b=>{let text=b.text.replace(/^(Ongoing|Past)\s*:\s*/,'');let parts=text.split(/(?=Project [Pp]artners?:|Supported by:?)/);return `<article class="project"><span class="tag">${b.text.startsWith('Ongoing')?'Ongoing':'Past'}</span><h2>${esc(parts[0])}</h2>${parts.slice(1).map(p=>`<p>${esc(p)}</p>`).join('')}${b.links.map(l=>link(l.url,l.text)).join('')}</article>`}).join('')}</div><section class="section"><h2>Our geographic footprint of engagement</h2>${img(research.map,'Map of IDEAS Lab geographic engagement','map')}</section></div>`;
 if(slug==='publications')return `<div class="wrap space-bottom"><div class="page-intro"><p class="eyebrow">Our work</p><h1>Publications</h1><p>${link(data('publications').blocks[1].links[0].url,'View the full publication list on Google Scholar ↗')}</p></div>${papers.map((p,i)=>`<article class="paper"><span class="number">0${i+1}</span><div><h2>${esc(p.title)}</h2><p class="authors">${esc(p.authors)}</p><details><summary>Read abstract</summary><p>${esc(p.abstract)}</p></details>${link(p.url,'Read the paper ↗')}</div></article>`).join('')}</div>`;
 if(slug==='news')return `<div class="wrap space-bottom"><div class="page-intro"><p class="eyebrow">From the lab</p><h1>News &amp; updates</h1><p>${esc(data('news').blocks[1].text)}</p></div>${newsGrid(posts)}</div>`;
 if(slug==='opportunities')return `<div class="wrap"><div class="page-intro"><p class="eyebrow">Join our community</p><h1>Current opportunities</h1></div><div class="prose"><div class="notice"><h2>Prospective students</h2><p>${esc(opportunities.blocks[1].text.replace(/^Prospective Students:\s*/,''))}</p></div><h2>Get in touch</h2><div class="contact"><p>${esc(opportunities.blocks[2].text)}</p><p>${link('mailto:'+opportunities.blocks[3].text,opportunities.blocks[3].text)}<br>${link('tel:+12066164502',opportunities.blocks[4].text)}</p></div></div></div>`;
 const p=posts.find(p=>'post/'+p.slug===slug);if(p)return `<article class="wrap"><div class="page-intro prose"><p class="eyebrow"><a href="${url('news')}">← All news</a></p><h1>${esc(p.title)}</h1>${p.paragraphs.map(t=>`<p>${esc(t)}</p>`).join('')}${p.images.map(i=>img(i,p.title)).join('')}${p.links.map(l=>`<p>${link(l.url,l.text)}</p>`).join('')}</div></article>`;
 return `<div class="wrap page-intro"><h1>Page not found</h1><p><a href="${url('')}">Return to the homepage</a></p></div>`;
}
const out=path.join(root,'out');fs.mkdirSync(out,{recursive:true});for (const f of fs.readdirSync(root)) { if (/\.(jpg|jpeg|png|css)$/i.test(f)) fs.copyFileSync(path.join(root,f),path.join(out,f)); }
const routes=[...nav.map(x=>x[0]),...posts.map(p=>'post/'+p.slug),'404'];
for(const slug of routes){prefix=slug==='404'?'./':'../'.repeat(slug.split('/').filter(Boolean).length)||'./';const title=nav.find(n=>n[0]===slug)?.[1]||posts.find(p=>'post/'+p.slug===slug)?.title||'Page not found';const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} | IDEAS Research Lab</title><meta name="description" content="Interdisciplinary Energy Analytics for Society at the University of Washington. Research advancing sustainable, inclusive, and equitable energy systems."><link rel="stylesheet" href="${prefix}styles.css"></head><body><a class="skip" href="#main">Skip to content</a><div class="institution"><div class="wrap">UNIVERSITY OF WASHINGTON · ELECTRICAL &amp; COMPUTER ENGINEERING</div></div><header class="header"><div class="wrap"><a class="brand" href="${url('')}" aria-label="IDEAS Research Lab home"><strong>IDEAS</strong><span>Research<br>Lab</span></a><nav class="nav" aria-label="Main navigation">${nav.map(([s,n])=>`<a href="${url(s)}" ${s===slug?'aria-current="page"':''}>${n}</a>`).join('')}</nav></div></header><main id="main">${render(slug)}</main><footer class="footer"><div class="wrap"><div><strong>IDEAS Research Lab</strong><p>Interdisciplinary Energy Analytics for Society</p><p class="copyright">© ${new Date().getFullYear()} IDEAS Lab</p></div><div><p>University of Washington<br>Paul Allen Center, 185 E Stevens Way NE AE100R<br>Seattle, WA 98195 · Room 215H</p><p><a href="mailto:jlukuyu@uw.edu">jlukuyu@uw.edu</a></p></div></div></footer></body></html>`;const dest=slug==='404'?path.join(out,'404.html'):path.join(out,slug,'index.html');fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,html);}
fs.writeFileSync(path.join(out,'.nojekyll'),'');console.log(`Built ${routes.length} static pages in out/`);
